# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [3]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(media_salarial)

3714.285714285714


In [8]:
# Identificar funcionários com salários acima da média, da o indice
funcionarios_acima_media = np.where(salarios > media_salarial)
print(funcionarios_acima_media)

(array([2, 4, 5, 6], dtype=int64),)


In [9]:
#caso queira os valores acima da media
print(salarios[funcionarios_acima_media])

[4000 4500 4000 5000]


In [10]:
#pode ser feito assim tambem
print(salarios[salarios > media_salarial])

[4000 4500 4000 5000]


In [12]:
#podemos concatenar textos no resultado
print(np.where(salarios > media_salarial, 'acima de média', 'abaixo de media'))

['abaixo de media' 'abaixo de media' 'acima de média' 'abaixo de media'
 'acima de média' 'acima de média' 'acima de média']


In [16]:
# dar bônus de 10% para os funcionários com salários abaixo da média
salarios_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios)
print(salarios_bonus)
print(salarios)

[3300. 3850. 4000. 2200. 4500. 4000. 5000.]
[3000 3500 4000 2000 4500 4000 5000]


In [23]:
# filtrar os salários entre 3000 e 4500 com where
salarios_entre_posicoes = np.where((salarios >= 3000) & (salarios <= 4000))
print(salarios_entre_posicoes)

(array([0, 1, 2, 5], dtype=int64),)


In [41]:
#se o salario estiver dentro da condicao recebe aumento de 5%
salarios_ajustados = np.where((salarios > 3000) & (salarios <= 4000), 
                              salarios * 1.05, salarios)
print(salarios)
print(salarios_ajustados)

[3000 3500 4000 2000 4500 4000 5000]
[3000. 3675. 4200. 2000. 4500. 4200. 5000.]


In [35]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where
print(np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4000)))

(array([2, 3, 4, 5, 6], dtype=int64),)


In [40]:
salarios_segundo_ajuste = np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4000),
                                   salarios_ajustados * 1.10, salarios)

print(salarios_segundo_ajuste)

[3000. 3500. 4620. 2200. 4950. 4620. 5500.]
